language: ruby

cache: bundler

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - bin/setup

script:
  - bundle exec rspec
  - bundle exec rubocop
